x-public_pb_instance_env: &public_pb_instance_env PUBLIC_PB_INSTANCE=${PUBLIC_PB_INSTANCE:-https://pb.bruum.cargoway.cloud}

services:
  pb:
    build: './pocketbase'
    container_name: 'bruum-pb-prod'
    restart: 'unless-stopped'
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.bruum-pb-prod.rule=Host(`pb.bruum.cargoway.cloud`)'
      - 'traefik.http.routers.bruum-pb-prod.entrypoints=https'
      - 'traefik.http.routers.bruum-pb-prod.tls.certresolver=letsencrypt'
      - 'traefik.http.routers.bruum-pb-prod.tls=true'
      - 'traefik.http.services.bruum-pb-prod.loadbalancer.server.port=8080'
    volumes:
      - './pocketdb:/app/pb_data'
    networks:
      - traefik

  # frontend:
  #   build:
  #     context: './'
  #     dockerfile: 'Dockerfile'
  #   container_name: 'bruum-frontend-dev'
  #   restart: 'unless-stopped'
  #   labels:
  #     - 'traefik.enable=true'
  #     - 'traefik.http.routers.bruum-frontend-prod.entrypoints=https'
  #     - 'traefik.http.routers.bruum-frontend-prod.tls=true'
  #     - 'traefik.http.routers.bruum-frontend-prod.tls.certresolver=letsencrypt'
  #     - 'traefik.http.routers.bruum-frontend-prod.rule=Host(`bruum.cargoway.cloud`)'
  #     - 'traefik.http.services.bruum-frontend-prod.loadbalancer.server.port=3000'
  #   depends_on:
  #     - pb
  #   environment:
  #     - *public_pb_instance_env
  #     - GSHEETS_APIKEY=${GSHEETS_APIKEY}
  #     - GSHEETS_CLIENTID=${GSHEETS_CLIENTID}

  frontend-prod:
    image: 'ghcr.io/vano2903/soapbox-website:latest'
    container_name: 'bruum-frontend-prod'
    restart: 'unless-stopped'
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.bruum-frontend-prod.entrypoints=https'
      - 'traefik.http.routers.bruum-frontend-prod.tls=true'
      - 'traefik.http.routers.bruum-frontend-prod.tls.certresolver=letsencrypt'
      - 'traefik.http.routers.bruum-frontend-prod.rule=Host(`bruum.cargoway.cloud`)'
      - 'traefik.http.services.bruum-frontend-prod.loadbalancer.server.port=3000'
    depends_on:
      - pb
    environment:
      - *public_pb_instance_env
      - GSHEETS_APIKEY=${GSHEETS_APIKEY}
      - GSHEETS_CLIENTID=${GSHEETS_CLIENTID}
    networks:
      - traefik

networks:
  traefik:
    external: true
    name: traefik-servicenet
